language: php
php:
- '5.5'
- '5.6'
- '7.0'
- hhvm
- nightly
cache:
  directories:
  - vendor
install:
- composer self-update
- composer global require "fxp/composer-asset-plugin:~1.1.1"
- composer install
before_script: if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi
script: composer exec "codecept run --coverage --coverage-xml"
after_success:
- composer exec "coveralls"
