language: php
php:
- '5.6'
- '7.0'
- hhvm
- nightly
install:
- composer self-update
- composer global require "fxp/composer-asset-plugin:~1.1.1"
- composer install
script: composer exec "codecept run"
