language: php
php:
- '5.5'
- '5.6'
- '7.0'
- hhvm
- nightly
matrix:
  allow_failures:
  - php: hhvm
install:
- composer self-update
- composer global require "fxp/composer-asset-plugin:~1.1.1"
- composer install
script: composer exec "codecept run"
